baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"
title = "J. Antonio Guzmán Q."
theme = "KeepIt"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
    
  [[menu.main]]
    name = "Research and Projects"
    url = "/categories/"
    weight = 2
    
  [[menu.main]]
    name = "Publications"
    url = "/publications"
    weight = 3
    
  [[menu.main]]
    name = "Software development"
    url = "/code"
    weight = 4

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 5

[params]
    since = 2018
    author = "J. Antonio Guzmán Q."               # Author's name
    avatar = "/images/me/myguzman3.jpg"           # Author's avatar
    subtitle = "J. Antonio Guzmán Q."       # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""

    description = "" # site description
    keywords = "Ph.D Candidate and Vanier Scholar at the University of Alberta" # site keywords

    license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.social]
    GitHub = "Antguz"
    Linkedin = "jantonioguzman"
    Twitter = "AntonioGuzman06"
    Stackoverflow = "3483096"
    ##gscholar = "Ev3ofxwAAAAJ"
    google-scholar = "Ev3ofxwAAAAJ"
    Email = "antguz06@gmail.com"
    Researchgate = "J_Antonio_Guzman_Q"
    

# Used only for Seo schema 
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
  name = "J. Antonio Guzmán Q."

  [params.publisher]
    name = "J. Antonio Guzmán Q."

    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  [params.logo]
    url = "logo.png"
    width = 127
    height = 40

  [params.image]
    url = "cover.png"
    width = 800
    height = 600
    
